#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d CODE WEB DISCORD HOME MUSIC EXTRA

# bspc config border_width         4
bspc config window_gap         	20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nm-connection-editor state=floating
bspc rule -a among us.exe state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# To start the daemon in the background
sxhkd &

# running compositor
picom -c -l0 -t0 -r0 -o.00

# Changing bg
nitrogen --set-scaled /usr/share/backgrounds/aipic.jpg

# polybar

# kill previous instances of polybar
pkill polybar

# run launch.sh
~/.config/polybar/launch.sh

# betterlockscreen
betterlockscreen &

# flameshot
flameshot &

# dunst
dunst &

# discord
# Discord
